<?php

/**
 * @file
 * Contains neo4j_friends.module.
 */

use Drupal\Component\Serialization\Json;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Adadgio\GraphBundle\ORM\Cypher;

/**
 * Implements hook_help().
 */
function neo4j_friends_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the neo4j_friends module.
    case 'help.page.neo4j_friends':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Neo4j Friends') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_entity_view_alter().
 */
function neo4j_friends_entity_view_alter(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display) {
  // Hide the realname field label in compact mode.
  if (isset($build['#user']) && $build['#view_mode'] == 'picture_and_name') {
    if (isset($build['realname'])) {
      $build['realname']['#label_display'] = 'hidden';
    }
  }
}

/**
 * Helper function to add a friend request.
 *
 * Equivalent Cypher query:
 * MATCH (u1:User {entity_id:{$uid1}}), u2:User {entity_id:{$uid2}}) CREATE UNIQUE (u1)-[:FRIEND {request:true}]-(u2)
 */
function _neo4j_friends_add_friend($uid1, $uid2) {
  $query = (new Cypher())
    ->match('u1', 'User', array('entity_id' => $uid1))
    ->match('u2', 'User', array('entity_id' => $uid2))
    ->getQuery();
  $query .= " CREATE UNIQUE (u1)-[:FRIEND {request:1}]-(u2)";
  return $query;
}

/**
 * Helper function to get confirmed friends.
 *
 * Equivalent Cypher query:
 * MATCH (n)-[rel:FRIEND]-(n1) WHERE n.entity_id = \"{$uid}\" AND NOT EXISTS(rel.request) RETURN collect(n1)
 */
function _neo4j_friends_get_friends($uid) {
  $query = (new Cypher())
    ->match('u')
      ->relatedWith('u1')
      ->by('r', 'FRIEND', array(), '-')
      ->where($uid, "u.entity_id =")
      ->andWhere("NOT EXISTS (r.request)")
      ->andReturn('collect(u1)')
    ->getQuery();

  return $query;
}

/**
 * Helper function to get pending friend invites.
 *
 * Equivalent Cypher query:
 * MATCH (n)-[rel:FRIEND {request:true}]->(n1) WHERE n.entity_id = {$uid} RETURN collect(n1)
 */
function _neo4j_friends_pending_invites($uid) {
  $query = (new Cypher())
    ->match('u')
      ->relatedWith('u1')
      ->by('r', 'FRIEND', array('request' => 1), '->')
      ->where($uid, "u.entity_id =")
      ->andReturn('collect(u1)')
    ->getQuery();
  return $query;
}

/**
 * Helper function to get pending friend invites.
 * @todo : only direction changes, might be merged with the above?
 *
 * Equivalent Cypher query:
 * MATCH (n)<-[rel:FRIEND {request:true}]-(n1) WHERE n.entity_id = {$uid} RETURN collect(n1)
 */
function _neo4j_friends_pending_requests($uid) {
  $query = (new Cypher())
    ->match('u')
      ->relatedWith('u1')
      ->by('r', 'FRIEND', array('request' => 1), '<-')
      ->where($uid, "u.entity_id =")
      ->andWhere("EXISTS (r.request)")
      ->andReturn('collect(u1)')
    ->getQuery();

  return $query;
}

/**
 * Helper function accept a friend request.
 *
 * Equivalent Cypher query:
 * MATCH (u1:User {entity_id:{$uid1}})-[r:FRIEND]-(u2:User {entity_id:{$uid2}}) REMOVE r.request
 */
function _neo4j_friends_accept_request($uid1, $uid2) {
  $query = (new Cypher())
    ->match('u1', 'User', array('entity_id' => $uid1))
      ->relatedWith('u2', 'User', array('entity_id' => $uid2))
      ->by('r', 'FRIEND', array('request' => 1), '<-')
      ->getQuery();
  $query .= " REMOVE r.request";
  return $query;
}

/**
 * Helper function to process collections.
 *
 * @todo : move to neo4j main module?
 */
function _process_collection($result) {
  $results = NULL;
  if ($result->hasRecord()) {
    $records = $result->records();
    $records = array_pop($records);
    if ($records->hasValues()) {
      $results = $records->values();
      $results = $results[0];
    }
  }
  return $results;
}
